### ISSUE TITLE
tetris demo arrow keys have no effect

### ISSUE THREAD

**Issue by jbclements** [racket/frtime#8]
In the tetris demo, running on 7.3 on Mac OS X 10.14.5, the arrow keys seem to have no effect on the game, although hitting a non-arrow key does cause a beep.

**Comment by ghcooper** [comment]
Although the graphics window opens in front of the main Racket window, I believe that you need to click the mouse in the graphics window to set focus before the keys can be "heard" by the demo. (As far as I know this is intended behavior on the part of DrRacket and/or the OS, not the result of anything peculiar that FrTime or the tetris example are doing with key event handling.)

**Comment by rfindler** [comment]
Would it work to add `(send canvas focus)` somewhere around [here](https://github.com/racket/frtime/blob/master/demos/tetris.rkt#L153)?

**Comment by samth** [comment]
That works for me.

**Comment by ghcooper** [comment]
Thanks, Robby and Sam. I've incorporated that change.
